source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'

gem 'dotenv-rails'
gem "octokit", "~> 3.0"
gem 'active_model_serializers'
gem 'rack-cors', :require => 'rack/cors'
gem 'faraday-http-cache'
gem 'unicorn'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
