source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'

gem 'dotenv-rails'
gem "octokit", "~> 3.0"
gem 'active_model_serializers'
gem 'rack-cors', :require => 'rack/cors'
gem 'faraday-http-cache'
gem 'unicorn'
gem "rack-timeout"

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
end

gem 'rails_12factor', group: :production
