Student.delete_all

Student.create!(firstname: "Emma", lastname: "Spencer", username: "enspencer", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Abby", lastname: "Howell", username: "abigezunt", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Bryce", lastname: "Lambert", username: "brycelambert", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Matt", lastname: "Clement", username: "darkmoves", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Rahul", lastname: "Horé", username: "o-i", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Cori", lastname: "Allen", username: "callen6", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Dan", lastname: "Crews", username: "dannycrews", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Blake", lastname: "Ruddock", username: "blakeruddock", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Michael", lastname: "Finneran", username: "MicFin", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Amal", lastname: "Hussein", username: "amalhussein", city: "Boston", session: "December 15, 2013", cohort: 1)
Student.create!(firstname: "Ben", lastname: "Winter", username: "bengwinter", city: "Boston", session: "December 15, 2013", cohort: 1)

Student.create!(firstname: "Anna", lastname: "Tsykalova", username: "tsyan", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Becky", lastname: "Bell", username: "beccalou", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Emilie", lastname: "Reiser", username: "emreiser", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Hongyu", lastname: "Zhou", username: "nevermore2014", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Jack", lastname: "Henley", username: "jhenley45", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Janice", lastname: "Smith", username: "jks8787", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Jordan", lastname: "Morano", username: "jordpo", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Laure", lastname: "Fischer", username: "LaureMFischer", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Matthew", lastname: "Higgins", username: "higginsmt", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Mike", lastname: "Stone", username: "mikestone14", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Praggya", lastname: "Barretto", username: "prbarretto", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Prescott", lastname: "Murphy", username: "prurph", city: "Boston", session: "April 1, 2014", cohort: 2)
Student.create!(firstname: "Yiyang", lastname: "Song", username: "songyiyang", city: "Boston", session: "April 1, 2014", cohort: 2)

Student.create!(firstname: "George", lastname: "Straehle", username: "gstraehle", city: "Boston", session: "July 11, 2014", cohort: 3)
Student.create!(firstname: "Kathleen", lastname: "Votolato", username: "kvotolato3", city: "Boston", session: "July 11, 2014", cohort: 3)
Student.create!(firstname: "Lisa", lastname: "Plesko", username: "lisaplesko", city: "Boston", session: "July 11, 2014", cohort: 3)
Student.create!(firstname: "Michael", lastname: "Talley", username: "miketalley", city: "Boston", session: "July 11, 2014", cohort: 3)
Student.create!(firstname: "Amanda", lastname: "McDermott", username: "apmcdermott", city: "Boston", session: "July 11, 2014", cohort: 3)
Student.create!(firstname: "Ethan", lastname: "Gould", username: "EthanGould", city: "Boston", session: "July 11, 2014", cohort: 3)

Student.create!(firstname: "Sarah", lastname: "Mele", username: "sassynerd13", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Kagayaki", lastname: "Kawabata", username: "krk324", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Clara", lastname: "Beyer", username: "csb324", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Emma", lastname: "Gardner", username: "emmagard", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Jodi", lastname: "Detch", username: "jdetch", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Brian", lastname: "Tenggren", username: "brimatteng", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Julie", lastname: "Soforenko", username: "juliesof", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Katryn", lastname: "McIntosh", username: "katrynmc", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Alexander", lastname: "Feinberg", username: "afeinber", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Nick", lastname: "Novak", username: "nnovak13", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Diarmuid", lastname: "McGann", username: "dmcgann1", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Zack", lastname: "Banton", username: "zhbanton", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Eric", lastname: "Rho", username: "EricRho", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Devin", lastname: "Dreszer", username: "devindreszer", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Max", lastname: "Kohl", username: "maxkohl88", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Blair", lastname: "Caple", username: "kaaterskil", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Jake", lastname: "Austin", username: "jakeaustin", city: "Boston", session: "September 18, 2014", cohort: 4)
Student.create!(firstname: "Ben", lastname: "White", username: "whtouche", city: "Boston", session: "September 18, 2014", cohort: 4)

# Student.create!(firstname: "Trinity", lastname: "Montoya", username: "trinityXmontoya", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Stephen", lastname: "Saunders", username: "urbantumbleweed", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Alex", lastname: "Shook", username: "alexshook", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Spencer", lastname: "James", username: "sjstebbins", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Nathan", lastname: "Plutzik", username: "nplutzik", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Derek", lastname: "DiGioia", username: "ddigioia", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "David", lastname: "Miller", username: "davidmiller11", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Ash", lastname: "Kamel", username: "ajkamel", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Stephen", lastname: "Marsh", username: "stephenhmarsh", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Jason", lastname: "Leibowitz", username: "jasonleibowitz", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Igor", lastname: "Yuzovitskiy", username: "ByteDown", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Ilana", lastname: "Seid", username: "ilanaseid", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Paul", lastname: "Lee", username: "pjwl33", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "David", lastname: "Kim", username: "davidakimbo", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Tadashi", lastname: "Okazaki", username: "originalblend337", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Jaime", lastname: "Cohenca", username: "jcohenca", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Vincent", lastname: "Trivett", username: "trivett", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Eric", lastname: "Resnick", username: "eres805", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Jesse", lastname: "Sessler", username: "jemise111", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Lance", lastname: "Jordan", username: "lacostenycoder", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Cat", lastname: "Gelinas", username: "catm705", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "David", lastname: "McCoy", username: "davidmccoy", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Jason", lastname: "Kaye", username: "JayK31", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Jon", lastname: "Bichar", username: "ghostropic", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Gerald", lastname: "Wolfe", username: "crywolfe", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Thomas", lastname: "Liou", username: "tliounyc", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Talal", lastname: "Chouhdury", username: "talalc", city: "New York City", session: "May 15, 2014")
# Student.create!(firstname: "Nicholas", lastname: "Lohr", username: "Citybeams", city: "New York City", session: "May 15, 2014")

# Student.create!(firstname: "Richard", lastname: "Hessler", username: "richessler", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Brett", lastname: "Wallace", username: "BYWallace", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Adam", lastname: "Barrett", username: "ab75173", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Alexi", lastname: "Phillipson", username: "alexi215", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Salil", lastname: "Doshi", username: "4S1D2", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Mikael", lastname: "Davis", username: "OKitsMikael", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Thomas", lastname: "Weaver", username: "thmsweaver", city: "Washington, DC", session: "July 11, 2014")
# Student.create!(firstname: "Elaine", lastname: "Fang", username: "ef718", city: "Washington, DC", session: "July 11, 2014")

Student.create!(city: "Boston, MA", firstname: "Jonathan", username: "jsyzer", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Lauren", username: "laurenfazah", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Holly", username: "hollym021980", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Matt", username: "mattmcdevitt93", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Shaai", username: "shaai", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Shayna", username: "shaynacummings", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Michael", username: "mrdor", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Jason", username: "fishermanswharff", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Carlos", username: "cxoltero", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Collin", username: "collinblinder", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "George", username: "gbanis", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Rebecca", username: "rpazyaquian", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Ilja", username: "iljagoushcha", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "William", username: "billy1339", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Avinash", username: "areddy14", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Corrine", username: "raielin", session: "December 19, 2014", cohort: 5)
Student.create!(city: "Boston, MA", firstname: "Cenk", username: "cyurtbil", session: "December 19, 2014", cohort: 5)

Student.create!(city: "Boston, MA", firstname: "Max", lastname: "Blaushild", username: "MaxBlaushild", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Kelly", lastname: "Bondanza", username: "kbondanza", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Annie", lastname: "Bourgeois", username: "annie-b", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Ashlinn", lastname: "Brennan", username: "asbren13", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Anne", lastname: "Brett", username: "lady3bean", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Anthony", lastname: "Broccoli", username: "abroccoli", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Ross", lastname: "Degnen", username: "RDegnen", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Ian", lastname: "Delairre", username: "idelairre", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Katy", lastname: "Feng", username: "Katyf", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Jonathan", lastname: "Gruta", username: "jcyeathatsme", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Brandon", lastname: "Koo", username: "brandonkoo", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Caitlyn", lastname: "Landry", username: "caitlynl22", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Doug ", lastname: "MacDonald", username:"HelixPenguin", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Jenny", lastname: "Marx", username: "jrutledg", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Pat", lastname: "Needham", username: "goodeats", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Cara", lastname: "Pacifico", username: "cgpacifico", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Nicole", lastname: "Pupillo", username: "npupillo", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Dan", lastname: "Stoppelman", username: "dstop75", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Charlie", lastname: "Talbot", username: "LookOut800", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Helen", lastname: "Thi", username: "hthi", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Susan", lastname: "Tran", username: "catiffles", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Daniel", lastname: "Tyson", username: "tys1019", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Gina", lastname: "Villarreal", username: "villanagi89", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Jason", lastname: "Weeks", username: "J-Weeks", session: "April 3, 2015", cohort: 6)
Student.create!(city: "Boston, MA", firstname: "Kevin", lastname: "Whelan", username: "kevin2098", session: "April 3, 2015", cohort: 6)
