Student.delete_all

Student.create!(firstname: "Emma", lastname: "Spencer", username: "enspencer", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Abby", lastname: "Howell", username: "abigezunt", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Bryce", lastname: "Lambert", username: "brycelambert", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Matt", lastname: "Clement", username: "darkmoves", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Rahul", lastname: "Horé", username: "o-i", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Cori", lastname: "Allen", username: "callen6", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Dan", lastname: "Crews", username: "dannycrews", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Blake", lastname: "Ruddock", username: "blakeruddock", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Michael", lastname: "Finneran", username: "MicFin", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Amal", lastname: "Hussein", username: "amalhussein", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Ben", lastname: "Winter", username: "bengwinter", city: "Boston", session: "December 15, 2013")
Student.create!(firstname: "Anna", lastname: "Tsykalova", username: "tsyan", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Becky", lastname: "Bell", username: "beccalou", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Emilie", lastname: "Reiser", username: "emreiser", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Hongyu", lastname: "Zhou", username: "nevermore2014", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Jack", lastname: "Henley", username: "jhenley45", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Janice", lastname: "Smith", username: "jks8787", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Jordan", lastname: "Morano", username: "jordpo", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Laure", lastname: "Fischer", username: "LaureMFischer", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Matthew", lastname: "Higgins", username: "higginsmt", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Mike", lastname: "Stone", username: "mikestone14", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Praggya", lastname: "Barretto", username: "prbarretto", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Prescott", lastname: "Murphy", username: "prurph", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "Yiyang", lastname: "Song", username: "songyiyang", city: "Boston", session: "April 1, 2014")
Student.create!(firstname: "George", lastname: "Straehle", username: "gstraehle", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Kathleen", lastname: "Votolato", username: "kvotolato3", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Lisa", lastname: "Plesko", username: "lisaplesko", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Michael", lastname: "Talley", username: "miketalley", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Amanda", lastname: "McDermott", username: "apmcdermott", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Ethan", lastname: "Gould", username: "EthanGould", city: "Boston", session: "July 11, 2014")
Student.create!(firstname: "Sarah", lastname: "Mele", username: "sarahchristine913", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Kagayaki", lastname: "Kawabata", username: "krk324", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Clara", lastname: "Beyer", username: "csb324", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Emma", lastname: "Gardner", username: "emmagard", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Jodi", lastname: "Detch", username: "jdetch", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Brian", lastname: "Tenggren", username: "brimatteng", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Julie", lastname: "Soforenko", username: "juliesof", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Katryn", lastname: "McIntosh", username: "testkitschen", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Alexander", lastname: "Feinberg", username: "afeinber", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Nick", lastname: "Novak", username: "nnovak13", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Diarmuid", lastname: "McGann", username: "dmcgann1", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Zack", lastname: "Banton", username: "zhbanton", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Eric", lastname: "Rho", username: "EricRho", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Devin", lastname: "Dreszer", username: "devindreszer", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Max", lastname: "Kohl", username: "maxkohl88", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Blair", lastname: "Caple", username: "kaaterskil", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Jake", lastname: "Austin", username: "jakeaustin", city: "Boston", session: "September 18, 2014")
Student.create!(firstname: "Ben", lastname: "White", username: "whtouche", city: "Boston", session: "September 18, 2014")

Student.create!(firstname: "Trinity", lastname: "Montoya", username: "trinityXmontoya", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Stephen", lastname: "Saunders", username: "urbantumbleweed", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Alex", lastname: "Shook", username: "alexshook", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Spencer", lastname: "James", username: "sjstebbins", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Nathan", lastname: "Plutzik", username: "nplutzik", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Derek", lastname: "DiGioia", username: "ddigioia", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "David", lastname: "Miller", username: "davidmiller11", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Ash", lastname: "Kamel", username: "ajkamel", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Stephen", lastname: "Marsh", username: "stephenhmarsh", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Jason", lastname: "Leibowitz", username: "jasonleibowitz", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Igor", lastname: "Yuzovitskiy", username: "ByteDown", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Ilana", lastname: "Seid", username: "ilanaseid", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Paul", lastname: "Lee", username: "pjwl33", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "David", lastname: "Kim", username: "davidakimbo", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Tadashi", lastname: "Okazaki", username: "originalblend337", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Jaime", lastname: "Cohenca", username: "jcohenca", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Vincent", lastname: "Trivett", username: "trivett", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Eric", lastname: "Resnick", username: "eres805", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Jesse", lastname: "Sessler", username: "jemise111", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Lance", lastname: "Jordan", username: "lacostenycoder", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Cat", lastname: "Gelinas", username: "catm705", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "David", lastname: "McCoy", username: "davidmccoy", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Jason", lastname: "Kaye", username: "JayK31", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Jon", lastname: "Bichar", username: "ghostropic", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Gerald", lastname: "Wolfe", username: "crywolfe", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Thomas", lastname: "Liou", username: "tliounyc", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Talal", lastname: "Chouhdury", username: "talalc", city: "New York City", session: "May 15, 2014")
Student.create!(firstname: "Nicholas", lastname: "Lohr", username: "Citybeams", city: "New York City", session: "May 15, 2014")

